SET FOREIGN_KEY_CHECKS = 0;
drop table if exists artist;
drop table if exists albumn;
drop table if exists forminfo;
drop table if exists label;
drop table if exists permission_profile;
drop table if exists played;
drop table if exists song;
drop table if exists stack;
drop table if exists user;
drop table if exists user_profile;
SET FOREIGN_KEY_CHECKS = 1;